version: '3'

services :
  app :
    env_file :
      - .env
    build :
      context : .
    ports :
      - "8000:8000"
    volumes :
      - ./app:/app

  proxy :
    build :
      context : ./proxy
    volumes :
      - ./app:/app/static
    ports :
      - "80:80"
    depends_on :
      - app



